### ISSUE TITLE
Running Eval mode issue

### ISSUE THREAD

**Issue by interactivetech** [valentin-deschaintre/multi-image-deepNet-SVBRDF-acquisition#1]
Hi there, 

Thanks for open sourcing this awesome project! I got an error when running the testModel.sh in eval mode, where when I want to process a .jpg image, it defaults to .png, even when I set the --imageFormat to jpg. 

I dug into the codebase, and I believe the issue occurs in line 176, where you construct the dataReader.dataset class. The argument `imageFormat = a.imageFormat` is not set in the class construction, which results in line 89 of dataReader.py always defaulting to look for .png formatted images.

Replacing line 176 as shown below should resolve this issue:
```data=dataReader.dataset(a.input_dir, imageType = a.imageFormat, imageFormat = a.imageFormat, trainFolder = a.trainFolder, testFolder = a.testFolder, inputNumbers = a.nbInputs, maxInputToRead = maxInputNb, nbTargetsToRead = a.nbTargets, cropSize=CROP_SIZE, inputImageSize=a.input_size, batchSize=a.batch_size, fixCrop = (a.mode == "test"), mixMaterials = (a.mode == "train"), fixImageNb = a.fixImageNb, logInput = a.useLog, useAmbientLight = a.useAmbientLight, jitterRenderings = a.jitterRenderings, firstAsGuide = False, useAugmentationInRenderings = not a.NoAugmentationInRenderings, mode = a.mode)```

**Comment by valentin-deschaintre** [comment]
Hi,

Thanks for pointing this out and your interest in our work. The bug came from a miss in the "cleanup" I did before publication, leading to two properties trying to control the same thing. imageFormat should now be properly connected!

Please let me know if it works for you.

**Comment by interactivetech** [comment]
I incorporated the fix locally, and it looks good to me! I will close the issue :).
